branch-defaults:
  master:
    environment: Georgia-Tech-Tutoring-A
global:
  application_name: Georgia-Tech-Tutoring-App
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v2.0.0 running PHP 5.6
  default_region: us-east-1
  profile: eb-cli
  sc: git
